Общие интерфейсы для парсеров (до 15.11)
DaniilShev/liquid-log pull request #4
Opened 2017-11-09 11:15 UTC by DaniilShev

Избавился от дублирования кода в swtich-case. 
Выполнил рефакторинг парсеров времени и данных. 
Но не стал переписывать парсеры данных для sdng (ActionsDoneParser и ErrorsParser), просто вызываю их из нового (SdngDataParser).

@ykalemi

## Задание

Для каждого режима парсинга (sdng, top, gc) есть два парсера - один читает из строки дату, другой - данные. Также, можно обратить внимание, что код внутри блоков switch-case очень похожий.

Нужно:

Выделить два интерфейса - DataParser, TimeParser.
Для каждого режима должен быть парсер реализующий соответствующий интерфейс
Избавиться от дублирования кода внутри блоков swtich-case

2017-11-09 12:23 UTC, ykalemi requested changes

2017-11-09 12:23 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/data/TopDataParser.java
> +        Matcher cpuAndMemMatcher = cpuAndMemPattren.matcher(line);
До этой строки дойдём только если loadAvgMatcher что-то нашёл. Но это означает, что cpuAndMemPattren в этой строке уже ничего не найдёт.

return всё-таки зря

2017-11-09 12:23 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/data/TopDataParser.java
> +    {
ещё я не уверен, что этот парсер у вас работает. Его принципиальное отличие в том, что "логи", которые он парсит - многострочные. Информация о дате есть только в первой строке "блока", далее построчно идёт информация, которая относится всё к той же дате.

Именно поэтому в оригинальном варианте TopParser сам обходил весь файл, в отличие от других парсеров.
Хорошо, что избавились от этого обхода, но данные он всё-таки должен сохранять

2017-11-09 12:23 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/data/SdngDataParser.java
> +        currentSet.getActionsDone().parseLine(line);
в принципе, можно же и для этих парсеров реализовать интерфейс. Тогда SdngDataParser будет таким композитным парсером.

2017-11-09 12:47 UTC, DaniilShev commented on src/main/java/ru/naumen/perfhouse/parser/data/TopDataParser.java
> +    {
Не открывал логи top, а надо было бы) Сейчас перепишу.

2017-11-09 12:51 UTC, DaniilShev commented on src/main/java/ru/naumen/perfhouse/parser/data/SdngDataParser.java
> +        currentSet.getActionsDone().parseLine(line);
Хм, не подумал о композитности. Реализую.

2017-11-12 18:03 UTC, DaniilShev commented
Исправил парсер логов top. Перестроил работу с парсерами sdng: сделал композитный класс для парсеров данных, для действий и ошибок сделал адаптеры с интерфейсом DataParser.

2017-11-13 07:07 UTC, ykalemi requested changes

2017-11-13 07:07 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/data/CompositeDataParser.java
> +        parsers = dataParsers;
Лучше так:
   DataParser... dataParsers

тогда в месте использования не нужно будет создавать массив руками

2017-11-13 07:07 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/Parser.java
> +                if (time != 0)
Мне больше нравился предыдущий вариант parseLine(line, ds), без setCurrentSet - это позволяло в будущем сделать все DataParser stateless, т.е. не хранящими никакое состояние.

Ещё один минус: раньше логика была такая - если в строке не удалось найти время, то значит, что в этой строе нет ничего интересного и мы её просто пропускаем (да, Top работал иначе, но все остальные парсеры именно так). Сейчас мы каждую строку всё равно проверим DataParser-ом.

Предложение такое: здесь лучше оставить как было, а переделать именно TopTimeParser - чтобы именно он запоминал последнее распарсенное время, и если в новой строке времени нет, то возвращал последнее сохранённое (именно в этом его логика ведь).

Тогда общий механизм будет выглядеть намного лучше

2017-11-13 08:40 UTC, DaniilShev commented
Не подумал о переделывании TopTimeParser. Да, такой подход выглядит заметно лучше.

2017-11-13 09:55 UTC, ykalemi commented
Да, выглядит отлично (надёюсь, работает так же))

2017-11-13 10:09 UTC, DaniilShev commented
Работает, я тестировал)

2017-11-13 10:14 UTC, merged