Меньшее потребление памяти при парсинге (до 22.11)
DaniilShev/liquid-log pull request #5
Opened 2017-11-13 13:57 UTC by DaniilShev

Перенёс работу с базой в отдельный класс Storage и покрыл его тестами.
![image](https://user-images.githubusercontent.com/10204278/32729012-3d418c94-c8a4-11e7-8b7c-f00523b05074.png)

## Задание

- Избавиться от накапливания данных, сохранять их, как только они готовы.
- Убрать всю работу с базой (InfluxDao) из класса App (вместе с предыдущим пунктом) в новый класс. У этого класса должен быть как минимум один публичный метод (но может быть и больше, зависит от реализации): DataSet get(long key);
- Покрыть новый класс тестами. Чтобы было удобно создавать моки, нужно выделить у InfluxDao интерфейс и его использовать в новом классе.
- Дать классу App название, более соответствующее его предназначению.

@ykalemi

2017-11-13 19:23 UTC, ykalemi requested changes

2017-11-13 19:23 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/influx/InfluxDAO.java
> +public class InfluxDAO implements InfluxDAOInterface
наименования - дело личное, в принципе. Но сейчас достаточно распространена такая практика - InfluxDao для интерфейса и InfluxDaoImpl для реализации

2017-11-13 19:23 UTC, ykalemi commented on src/test/java/ru/naumen/perfhouse/parser/StorageTest.java
> +        firstSet.getGc().addValue(1.5);
а эти getGC().addValue как-то влияют на результат теста? Или это для того, чтобы пройти !gc.isNan() ?

2017-11-13 19:23 UTC, ykalemi commented on src/test/java/ru/naumen/perfhouse/parser/StorageTest.java
> +        firstSet.getActionsDone().parseLine("Done(10): AddObjectAction");
тут я тоже пока до конца не разорался. Но хочу чтобы вы написали такой тест:

storage.get(1);
storage.get(2);
storage.save(1);

и проверить, сколько было вызовов
influxDAO.storeActionsFromLog

2017-11-13 19:29 UTC, DaniilShev commented on src/test/java/ru/naumen/perfhouse/parser/StorageTest.java
> +        firstSet.getGc().addValue(1.5);
Да, это для того, чтобы пройти проверку !gc.isNan(), чтобы потом проверить был ли вызов storeGc

2017-11-13 19:42 UTC, DaniilShev commented on src/test/java/ru/naumen/perfhouse/parser/StorageTest.java
> +        firstSet.getActionsDone().parseLine("Done(10): AddObjectAction");
Без теста скажу, что это баг, и последний DataSet просто не будет сохранён. Я не предусмотрел эту ситуацию в коде, и соответственно не покрыл её тестами.

2017-11-13 20:50 UTC, DaniilShev commented
Я пофиксил баг с сохранением последнего ДатаСета, и добавил соответствующий тест.

2017-11-14 03:35 UTC, ykalemi commented on src/test/java/ru/naumen/perfhouse/parser/StorageTest.java
> +        Mockito.verify(mockedInfluxDao).storeActionsFromLog(batchPoint, "test", 1,
в принципе, для всех аргументов можно сказать Mockito.any - так как в данном конкретном тесте нам интересно скорее количество вызовов. Хотя подробный тест лучше.

2017-11-14 03:35 UTC, ykalemi commented on src/test/java/ru/naumen/perfhouse/parser/StorageTest.java
> +    private InfluxDAO mockedInfluxDao;
Все ок. Можно еще добавить негативных сценариев
- сохранили сразу после создания
- все данные были Nan

2017-11-16 07:36 UTC, ykalemi approved these changes
всё отлично, можно немного улучшить - и мёрджить (или наоборот)

2017-11-16 07:36 UTC, ykalemi commented on src/test/java/ru/naumen/perfhouse/parser/StorageTest.java
> +        Storage storage = new Storage(mockedInfluxDao);
Раз у вас уже нет спешки по задачам, давайте улучшим этот тесткейс. Вот этот код вызывается в каждом тесте:

```
Storage storage = new Storage(mockedInfluxDao);
storage.init("test", false);
```

можно смело убрать в before?

2017-11-18 21:18 UTC, DaniilShev commented
Я убрал `Storage storage = new Storage(mockedInfluxDao);`. А вот для того, чтобы убрать `storage.init("test", false);`, я добавил в метод save() реинициализацию batchPoints.

По хорошему она там и так нужна, но в силу текущей архитектуры парсера не требуется.
Добавил соответствующий тест.

2017-11-19 06:15 UTC, ykalemi commented
> По хорошему она там и так нужна
а зачем? Мне казалось: save - окончание работы. А мы еще один Batch создаем?

2017-11-19 10:36 UTC, DaniilShev commented
> а зачем? Мне казалось: save - окончание работы. А мы еще один Batch создаем?

Для парсера, save - окончание работы. Но само по себе хранилище не должно ломаться при сохранении, по названию save не скажешь, что его можно вызвать единожды. Можно пойти другим путём и переименовать save в close.

2017-11-19 10:45 UTC, DaniilShev commented
Я подумал, и всё-таки переименовал save в close, убрав от туда создание нового BatchPoints. Но у меня сейчас почти готово 6 задание, не хочется создавать для него отдельную ветку для того, чтобы закоммитить эти изменения в этот issue.

2017-11-19 17:12 UTC, ykalemi approved these changes
Отдельная ветка на каждое задание не такая плохая идея ;-)

2017-11-19 17:38 UTC, merged

2017-11-20 06:33 UTC, ykalemi commented
Я только сейчас понял в чём проблема класса Storage у вас - он же синглтон. Но при этом хранит состояние каждого парсинга. При многопоточной обработке это всё сломается, конечно.

Для простоты я мог бы предложить пока не делать этот класс spring-бином, а создавать его на каждую обработку. (ну или вы сами можете придумать более корректное решение)