Каждый DataParser -> Spring Bean (до 29.11)
DaniilShev/liquid-log pull request #6
Opened 2017-11-25 14:44 UTC by DaniilShev

Я отделил логику парсеров ActionDoneParser и ErrorParser от данных которые они сохраняют. Сделал парсеры данных Spring Bean'ами. Сделал Storage обратно однопоточным, но теперь он имеет scope - запрос.

## Задание

Напомню глобальную цель, которая стоит перед вами “вы решили доработать это приложение таким образом, чтобы оно могло парсить почти любые логи”. Т.е. нужно сделать логику парсеров расширяемой и не зависящей от конкретного парсера.

В данном задании нужно сделать каждый парсер отдельным Spring Bean-ом, который не должен хранить никакого состояния (текущий DataSet, например). Это должен быть singleton, способный одновременно обрабатывать несколько файлов лога.

@ykalemi

2017-11-25 17:21 UTC, ykalemi requested changes

2017-11-25 17:21 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> -    @Inject
👍

2017-11-25 17:21 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/Storage.java
> +    @PreDestroy
Spring не гарантирует, что этот метод будет вызван при завершении обработки запроса. Да, бин будет уничтожен после обработки, но когда-то после. Поэтому не стоит привязывать логику на такое поведение, лучше вызывать сохранение явно.

Еще можно посмотреть на RequestContextListener

2017-11-25 17:21 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/dataparsers/ActionDoneDataParser.java
> +    private Pattern doneRegEx = Pattern.compile("Done\\((\\d+)\\): ?(.*?Action)");
можно сделать константой

2017-11-25 17:21 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/dataparsers/ErrorDataParser.java
> +    private Pattern warnRegEx = Pattern.compile("^\\d+ \\[.+?\\] \\(.+?\\) WARN");
тоже константы

2017-11-25 17:21 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/Parser.java
> +                dataParser = factory.getBean(GCDataParser.class);
не обязательно каждый bean запрашивать через factory, тем более что они все singleton. Но ок, пусть будет, в следущих задачах изменим

2017-11-25 18:55 UTC, DaniilShev commented on src/main/java/ru/naumen/perfhouse/parser/Storage.java
> +    @PreDestroy
Я посмотрел на RequestContextListener. Но верну так, как было, потому что было интуитивнее.

2017-11-25 20:24 UTC, DaniilShev commented
>Можно сделать константой

Сделал константами регулярные выражения в парсерах данных. 

>Spring не гарантирует, что этот метод будет вызван при завершении обработки запроса. 

Убрал PreDestroy из Storage.

>Не обязательно каждый bean запрашивать через factory

Переписал, теперь получаю их через Autowired и сохраняю в парсере, чтоб по сто раз не получать.

Немного улучшил UI и пофиксил в нём баг с поломанными кастомными запросами.

2017-11-26 07:54 UTC, ykalemi approved these changes

2017-11-26 08:18 UTC, merged