Своя реализация DataSet для каждого DataParser (до 06.12)
DaniilShev/liquid-log pull request #7
Opened 2017-12-04 14:51 UTC by DaniilShev

Выполнил задание, попутно поправив тесты. В Storage убрал из них те, что тестируют функционал других классов.
Текущая версия полностью рабочая, но в некоторых местах компилятор ругается, что тип generic не точный (`Warning:(113, 17) Unchecked call to 'parseLine(String, T)' as a member of raw type 'ru.naumen.perfhouse.parser.DataParser'`)

##Задание

- DataSet должен стать интерфейсом.
- Для создания конкретного DataSet нужна фабрика - см. шаблон “Фабричный метод”.
- Остался вопрос с сохранением - здесь для каждого режима парсинга создать отдельный spring bean (аналогично DataParser-ам).
- И не забывайте про generics! (ну, или почитайте про них) В интерфейсе DataParser должен использоваться интерфейс DataSet. А в конкретной реализации DataParser (например, TopParser) - конкретный DataSet (например, TopDataSet)

@ykalemi

2017-12-04 17:16 UTC, ykalemi requested changes
в принципе ок, но есть один вопрос

2017-12-04 17:16 UTC, ykalemi commented on src/test/java/ru/naumen/perfhouse/parser/StorageTest.java
> -    public void mustStoreGc() {
можно было, конечно, сделать новые тесты под те классы, которые здесь проверяются. А не просто удалять

2017-12-04 17:16 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/sets/TopDataSet.java
> +    public TopData getData() {
а нужен этот метод getData? Почему TopData не может быть сразу реализацией DataSet?

2017-12-05 08:42 UTC, DaniilShev commented on src/main/java/ru/naumen/perfhouse/parser/sets/TopDataSet.java
> +    public TopData getData() {
Если убрать единый для всех DataSet метод getData, наличие интерфейса теряет почти весь смысл. Классы с данным интерфейсом не будут предоставлять ни единого общего метода.
Тогда DataSet будет просто играть роль единого базового интерфейса.

2017-12-05 08:44 UTC, DaniilShev commented on src/test/java/ru/naumen/perfhouse/parser/StorageTest.java
> -    public void mustStoreGc() {
Верну следующим коммитом

2017-12-05 09:12 UTC, DaniilShev commented on src/main/java/ru/naumen/perfhouse/parser/sets/TopDataSet.java
> +    public TopData getData() {
>Тогда DataSet будет просто играть роль единого базового интерфейса.

Хотя большего действительно не нужно. Я перепишу их для Top и GC.
Но всё равно придётся оставить SdngDataSet в каком-то виде.

2017-12-05 18:24 UTC, ykalemi approved these changes

2017-12-05 18:24 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/parser/Parser.java
> +                parserFactory = new SdngParserFactory();
кажется, эти фабрики вполне могут быть бинами. Но это уже другая задача

2017-12-05 20:40 UTC, DaniilShev commented on src/main/java/ru/naumen/perfhouse/parser/Parser.java
> +                parserFactory = new SdngParserFactory();
Я думал их сделать бинами, но увидел следующую задачу и решил не торопиться.

2017-12-05 20:40 UTC, merged